easifem/base

- pages/Installation_Linux.md
- setup/Ubuntu.sh
> :wo linux build

- setup.py
- setup/set_envvar_Ubuntu.sh
Improvement in setup.py for linux build
> :wo on linux build of easifemBase

- install.py
- pages/Installation_Linux.md
- setup.py
> :wo install.py

- install.py
> :wo linux build of easifemBase

- CMakeLists.txt
- pages/Installation_Linux.md
- setup/install_pkgs_Ubuntu.sh
- src/modules/CMakeLists.txt
- src/modules/Gnuplot/CMakeLists.txt
- src/submodules/CMakeLists.txt
modifying setup.py and install.py
> :wo linux installation of easifemBase

- src/modules/CSRMatrix/src/CSRMatrix_Method.f90
- src/submodules/CSRMatrix/CMakeLists.txt
- src/submodules/CSRMatrix/src/CSRMatrix_Method@LUsolveMethods.f90
- src/submodules/CSRMatrix/src/CSRMatrix_Method@MatvecMethods.f90
- src/submodules/CSRMatrix/src/CSRMatrix_Method@getMethod.f90
- tests/testCSRMatrix/test_CSRMatrix.f90
Added LUSolve, MatVec to CSRMatrix_
> added LUSOLVE, Matvec, CSRMatrix

- CMakeLists.txt
- install.py
- setup.py
- setup/install_pkgs_Ubuntu.sh
- setup/set_envvar_Ubuntu.sh
- src/modules/BLAS/src/BLAS1V_Method.f90
- src/modules/GlobalData/src/GlobalData.f90
- src/modules/Utility/src/Utility.f90
- src/submodules/BLAS/src/BLAS1V_Method@Methods.f90
- src/submodules/Utility/src/Utility@Misc.f90
- src/submodules/Utility/src/Utility@StringMethods.f90
added methods for string manipulation.
> added  stringMethods

- .vscode/settings.json
- src/modules/DOF/src/DOF_Method.F90
- src/submodules/DOF/src/DOF_Method@IO.F90
This is related to Issue #56 
Regards
Vikas
> minor modification in `DOF_Method` module

- .github/.labeler.yml
- .github/workflows/labeler.yml
I am adding github action for adding labels on PR when there are changes in the dirs.
> Work action labels on files

- src/modules/DiffusionMatrix/src/DiffusionMatrix_Method.F90
- src/modules/Polynomial/src/HexahedronInterpolationUtility.F90
- src/modules/Polynomial/src/OrthogonalPolynomialUtility.F90
- src/modules/Polynomial/src/TriangleInterpolationUtility.F90
- src/submodules/Polynomial/src/HexahedronInterpolationUtility@Methods.F90
- src/submodules/Polynomial/src/TriangleInterpolationUtility@Methods.F90
Updates in ReferenceHexahedron ¥
Updates in HexahedronInterpolationUtility
Closing #231  #230  #163
> Updates in Hexahedron

- src/modules/Geometry/src/ReferenceLine_Method.F90
- src/modules/Geometry/src/ReferenceQuadrangle_Method.F90
- src/modules/GlobalData/src/GlobalData.F90
- src/modules/Polynomial/src/LineInterpolationUtility.F90
- src/modules/Polynomial/src/QuadrangleInterpolationUtility.F90
- src/modules/Polynomial/src/TriangleInterpolationUtility.F90
- src/submodules/Geometry/src/ReferenceLine_Method@Methods.F90
- src/submodules/Geometry/src/ReferenceQuadrangle_Method@Methods.F90
- src/submodules/Geometry/src/modified_burkardt.inc
- src/submodules/Polynomial/src/LineInterpolationUtility@Methods.F90
- src/submodules/Polynomial/src/QuadrangleInterpolationUtility@Methods.F90
- src/submodules/Polynomial/src/TriangleInterpolationUtility@Methods.F90
In this pull request I have introduced interesting updates related to the interpolation (polynomial) utility.
- QuadraturePoint_Line
- QuadraturePoint_Quadrangle
- LagrangeEvallAll_Quadrangle
Regards
Vikas
> Updates in Interpolation related methods

- src/modules/Geometry/src/ReferenceElement_Method.F90
- src/submodules/Geometry/CMakeLists.txt
- src/submodules/Geometry/src/ReferenceElement_Method@EnquireMethods.F90
- src/submodules/Geometry/src/ReferenceElement_Method@GeometryMethods.F90
Closing #254 
Following methods have been added.
- ElementName
- ElementType
- GetTotalNodesInElement
- ElementOrder
- XiDimension
- ElementTopology
- isVolume
- isLine
- isSurface
- isPoint
- isTriangle
- isQuadrangle
- isTetrahedron
- isHexahedron
- isPrism
- isPyramid
- isSerendipityElement
> Updates in ReferenceElement_Method

- src/modules/Utility/src/ConvertUtility.F90
- src/submodules/FEVariable/src/FEVariable_Method@ConstructorMethods.F90
Adding documentation in convert_2
> Update in ConvertUtility

- src/modules/CSRMatrix/src/CSRMatrix_ConstructorMethods.F90
- src/modules/RealVector/src/RealVector_Blas1Methods.F90
- Minor fixes in csrmatrix 
- Minor fixes RealVector_Blas1 method
> Minor Fixes

- src/modules/Utility/src/StringUtility.F90
- src/submodules/Utility/src/StringUtility@Methods.F90
> Updates in String Utility

- src/modules/CSRMatrix/src/CSRMatrix_GetMethods.F90
- src/modules/CSRMatrix/src/CSRMatrix_SetMethods.F90
- src/submodules/CSRMatrix/src/CSRMatrix_GetMethods@Methods.F90
- src/submodules/CSRMatrix/src/CSRMatrix_SetMethods@Methods.F90
- Updates in GetValue methods: Adding Get9 and Get10 method
- Update in Set4
> Updates in CSRMatrix_Method

- src/modules/Geometry/src/ReferenceQuadrangle_Method.F90
- src/submodules/Geometry/src/ReferenceHexahedron_Method@Methods.F90
- src/submodules/Geometry/src/ReferenceQuadrangle_Method@Methods.F90
- src/submodules/Geometry/src/ReferenceTetrahedron_Method@Methods.F90
Updates in ReferenceElements 
- Minor updates in ReferenceQuadrangle_Method, Adding HelpFaceData_Quadrangle, Adding FaceShapeMetaData_Quadrangle
- Updating face connectivity in hexahedron and tetrahedron
> Updates in ReferenceElement

- cmake/addLIS.cmake
> updates in cmake

- src/modules/Display/src/Display_Method.F90
- adding Display methods for complex number
> Updates in Display methods

- release_install.py
- src/modules/Lapack/src/GE_EigenValueMethods.F90
- src/submodules/Lapack/src/GE_EigenValueMethods@Methods.F90
- adding `destroy` argument  
- this is additional correction for #311
> Updates in EigenValueMethods
